name: "Test Check Copyright Pre-Commit"
on:
  workflow_dispatch:
  pull_request:
    paths:
      - "pre_commit_scripts/**"

jobs:
  test:
    name: "Run tests for check copyright pre-commit code"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - shell: bash
        run: |
          set -x # print commands that are executed
          $CONDA/bin/conda init
          source /home/runner/.bashrc
          pip install pytest
          python -m pytest -v -p no:warnings pre_commit_scripts/test_check_copyright.py
